publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

locale: 'it'

media_library:
  name: cloudinary
  config:
    cloud_name: succimas
    api_key: 767197248277585

collections:
  - label: 'Settings'
    name: 'settings'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - label: Site Name
            name: name
            widget: string
            hint: 'This is used for the site title'
          - label: Description
            name: description
            widget: string
            hint: 'This is used as descriptive text for links that link to this site'
          - label: Language
            name: lang
            widget: string
            pattern:
              - '^[a-z]{2}([-])?([A-Za-z]{2})?$'
              - 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'
          - label: Logo
            name: logo
            widget: 'image'
            allow_multiple: false
          - label: Email
            name: email
            widget: string
          - label: Phone
            name: phone
            widget: string
          - label: Codice Fiscale
            name: cod_fiscale
            widget: string
          - label: Partita Iva
            name: p_iva
            widget: string
          - label: Google Analytics ID
            name: analytics_id
            widget: string
            required: false
          - label: Default Sharing Image
            name: default_image
            widget: string
            required: false
          - label: 'Sitemap'
            name: 'sitemap'
            widget: 'list'
            required: false
            fields:
              - label: Name
                name: name
                widget: string
                required: false
              - label: Url
                name: url
                widget: string
                required: false
          - label: 'Social Links'
            name: 'socials'
            widget: 'list'
            required: false
            fields:
              - label: Name
                name: name
                widget: string
                required: false
              - label: Url
                name: url
                widget: string
                required: false
  - label: 'Relations'
    name: 'relations'
    files:
      - label: 'Agencies'
        name: 'agencies'
        file: 'assets/content/relation_files/agencies.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - label: 'Agencies'
            name: 'agencies'
            widget: 'list'
            required: false
            fields:
              - label: Name
                name: name
                widget: string
              - label: slug
                name: slug
                widget: string
                pattern:
                  - '^[a-z0-9-]+$'
                  - 'Must be digit and letter only, lowercase, and contains dash "-"'
      - label: 'Clients'
        name: 'clients'
        file: 'assets/content/relation_files/clients.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - label: 'Clients'
            name: 'clients'
            widget: 'list'
            required: false
            fields:
              - label: Name
                name: name
                widget: string
              - label: slug
                name: slug
                widget: string
                pattern:
                  - '^[a-z0-9-]+$'
                  - 'Must be digit and letter only, lowercase, and contains dash "-"'
              - label: 'Show on frontpage'
                name: 'show'
                widget: 'boolean'
                default: false
                required: false
              - label: 'Logo'
                name: 'logo'
                widget: 'image'
                required: false
                allow_multiple: false
  - name: 'blog'
    label: 'Blog'
    folder: 'assets/content/blog'
    format: 'json'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'works'
    label: 'Works'
    label_singular: 'Work'
    folder: 'assets/content/work'
    create: true
    format: 'json'
    slug: '{{project_type}}-{{slug}}'
    preview_path: 'work/{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - label: 'Project Type'
        name: 'project_type'
        widget: 'select'
        default: 'animation'
        options:
          - { label: 'Animation', value: 'animation' }
          - { label: 'Photo', value: 'photo' }
          - { label: 'Reel', value: 'reel' }
          - { label: 'Story', value: 'story' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'markdown',
          required: false,
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: 'Agency'
        name: 'agency'
        widget: 'relation'
        collection: 'relations'
        file: 'agencies'
        required: false
        search_fields: ['agencies.*.name']
        display_fields: ['agencies.*.name']
        value_field: 'agencies.*.name'
      - label: 'Client'
        name: 'client'
        widget: 'relation'
        collection: 'relations'
        file: 'clients'
        required: false
        search_fields: ['clients.*.name']
        display_fields: ['clients.*.name']
        value_field: 'clients.*.name'
      - label: 'Metadata'
        name: 'metadata'
        widget: 'object'
        required: false
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: false }
          - {
              label: 'Description',
              name: 'description',
              widget: 'string',
              required: false,
            }
      - label: 'Extras'
        name: 'extras'
        widget: 'list'
        minimize_collapsed: true
        required: false
        max: 3
        min: 1
        field:
          {
            label: 'Column',
            name: 'column',
            widget: 'markdown',
            required: false,
          }
      - label: 'Cover'
        name: 'cover'
        widget: 'object'
        required: false
        fields:
          - { label: 'Title', name: 'title', widget: 'string', required: false }
          - {
              label: 'Subtitle',
              name: 'subtitle',
              widget: 'string',
              required: false,
            }
          - label: 'Text Color'
            name: 'text_color'
            widget: 'select'
            default: 'black'
            options:
              - { label: 'Black', value: 'black' }
              - { label: 'White', value: 'white' }
              - { label: 'Gray', value: 'gray' }
              - { label: 'Red', value: 'red' }
              - { label: 'Yellow', value: 'yellow' }
              - { label: 'Green', value: 'green' }
              - { label: 'Blue', value: 'blue' }
              - { label: 'Indigo', value: 'indigo' }
              - { label: 'Purple', value: 'purple' }
              - { label: 'Pink', value: 'pink' }
          - label: 'Image'
            name: 'image'
            widget: 'image'
            required: false
            allow_multiple: false
      - label: 'Video'
        name: 'video'
        widget: 'object'
        required: false
        fields:
          - label: 'Type'
            name: 'type'
            widget: 'select'
            default: 'vimeo'
            required: false
            options:
              - { label: 'Vimeo', value: 'vimeo' }
          - { label: 'Title', name: 'title', widget: 'string', required: false }
          - { label: 'Cover', name: 'cover', widget: 'image', default: false }
          - { label: 'Url', name: 'url', widget: 'string', required: false }
          - { label: 'ID', name: 'id', widget: 'string', required: false }
      - label: 'Gallery'
        name: 'gallery'
        widget: 'object'
        required: false
        fields:
          - label: 'Grid Columns'
            name: 'columns'
            widget: 'number'
            default: 2
            value_type: 'int'
            min: 1
            max: 6
            step: 1
          - label: 'Items'
            name: 'items'
            widget: 'list'
            required: false
            fields:
              - {
                  label: 'Title',
                  name: 'title',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Alt Text',
                  name: 'alt',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Fullwidth',
                  name: 'fullwidth',
                  widget: 'boolean',
                  default: false,
                }
              - label: 'Ratio'
                name: 'ratio'
                widget: 'select'
                default: 'square'
                required: false
                options:
                  - { label: 'Square', value: 'square' }
                  - { label: '16by9', value: 'video' }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: 'image',
                  default: false,
                }
      - label: 'Credits'
        name: 'credits'
        widget: 'list'
        minimize_collapsed: true
        required: false
        max: 3
        min: 1
        field:
          {
            label: 'Column',
            name: 'column',
            widget: 'markdown',
            required: false,
          }
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About Page'
        name: 'about'
        format: 'json'
        file: 'assets/content/about.json'
        fields:
          - { label: Title, name: title, widget: string }
          - label: 'Description'
            name: 'description'
            widget: 'string'
            required: false
          - { label: Intro, name: intro, widget: markdown, required: false }
          - label: 'Cover'
            name: 'cover'
            widget: 'object'
            required: false
            fields:
              - {
                  label: 'Title',
                  name: 'title',
                  widget: 'string',
                  required: false,
                }
              - {
                  label: 'Subtitle',
                  name: 'subtitle',
                  widget: 'string',
                  required: false,
                }
              - label: 'Text Color'
                name: 'text_color'
                widget: 'select'
                default: 'black'
                options:
                  - { label: 'Black', value: 'black' }
                  - { label: 'White', value: 'white' }
                  - { label: 'Gray', value: 'gray' }
                  - { label: 'Red', value: 'red' }
                  - { label: 'Yellow', value: 'yellow' }
                  - { label: 'Green', value: 'green' }
                  - { label: 'Blue', value: 'blue' }
                  - { label: 'Indigo', value: 'indigo' }
                  - { label: 'Purple', value: 'purple' }
                  - { label: 'Pink', value: 'pink' }
              - label: 'Image'
                name: 'image'
                widget: 'image'
                required: false
                allow_multiple: false
